version: '3.5'
services:
  redis:
    image: redis:3.2
    container_name: superset_redis
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
  postgres:
    image: postgres:9.6
    container_name: superset_postgres
    environment:
      - POSTGRES_DB=superset
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset
      - PGDATA=/data
    volumes:
      - ./postgres:/data
  superset:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: superset_webserver
    depends_on:
      - postgres
    environment:
      - MAPBOX_API_KEY=${MAPBOX_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - ADMIN_USER=${ADMIN_USER} 
      - ADMIN_FNAME=${ADMIN_FNAME} 
      - ADMIN_LNAME=${ADMIN_LNAME} 
      - ADMIN_EMAIL=${ADMIN_EMAIL} 
      - ADMIN_PW=${ADMIN_PW} 
    volumes:
      - ./config/superset_config.py:/home/superset/superset_config.py
    ports:
      - 8088:8088

