version: '3.5'
services:
  postgres:
    image: postgres:9.6
    container_name: superset_postgres
    environment:
      - POSTGRES_DB=superset
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset
  superset:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: superset_webserver
    depends_on:
      - postgres
    environment:
      - MAPBOX_API_KEY=${MAPBOX_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./config/superset_config.py:/home/superset/superset_config.py

    ports:
      - "8088:8088"

